### ISSUE TITLE
main menu missing. Ubuntu 20.04 with Unity7

### ISSUE THREAD

**Issue by pixelr0** [MrCarroll/pinta-snap#1]
the main menu is missing (should be shown in the top bar) 
i'm using Ubuntu 20.04 with Unity7, pinta-james-carroll latest/stable:    1.7 2020-08-09 (1) 196MB -

![menu](https://user-images.githubusercontent.com/333589/89727286-c6ae9300-da2b-11ea-95e2-5177d19e625c.png)

left pinta snap, right pinta deb 1.6

**Comment by pixelr0** [comment]
maybe you need to add plugs: unity7 in snapcraft.yaml? (i don't know snaps stuff)

plugs: 
      - home
      - removable-media
      - x11
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - unity7

**Comment by pixelr0** [comment]
https://snapcraft.io/docs/desktop-interfaces

unity7: access to X, Unity services, a11y, input methods (ibus, fcitx, etc) and other legacy desktop methods

**Comment by JGCarroll** [comment]
Thanks for the report.

I think you're probably right about adding the unity7 interface; whilst desktop and desktop-legacy overlap with it heavily, I think the HUD integration is probably unique to that interface and would hopefully fix your problem.

Whilst this should be the easiest thing to update in the world given it's just adding one line to the Snapcraft definition and running Snapcraft again, there's an issue currently building with the LXD backends due to some faulty configuration on Ubuntu's end, which means I won't be able to get around to it until that's sorted. Once it is, I'll ping back here when the updated version is live to see if it fixes the problem.

**Comment by pixelr0** [comment]
great./ there's no rush, take your time

**Comment by JGCarroll** [comment]
Revision 2 with the unity7 interface should be live on the store now, hopefully it should fix the problem for you; it works on the testing I just did. You can hurry along the update with `sudo snap refresh`

**Comment by pixelr0** [comment]
yep, works fine now! THANKS

![great](https://user-images.githubusercontent.com/333589/89898126-d7f0ce80-dbe8-11ea-8456-33be9bdd8813.png)
