### ISSUE TITLE
Pinta not able to open screenshots

### ISSUE THREAD

**Issue by TIMAI2** [MrCarroll/pinta-snap#13]
Just upgraded to Xubuntu 24.04, which wiped my previous install of pinta, so installed your snap.

If I take a screenshot with ALT_PrtScr, I am offered to open the screenshot with Pinta. This does not work, no access to file. (This used to work before upgrading). I tried setting `snap connect pinta:removable-media` but no change. If I go into /tmp, where the screenshots are stored, and change permissions for the file from `None` to `Read & Write`, then Pinta can open it.

**Comment by JGCarroll** [comment]
Could you elaborate a bit more on the Read & Write permissions being involved please?

I'm surprised that works, because `/tmp` in snaps is unfortunately plagued by subtleties caused by the fact that the snap sees a different `/tmp` than what you do in the normal environment. `/tmp` inside the Snap is actually something like `/tmp/snap.pinta` in your host environment.

I'm assuming what might be happening is you're making the change and then proceeding to open the file via the GUI? When done with File > Open, there's mechanisms in place that let the Snap view files anywhere in your system in a safe manner that only gives it the singular file selected. This works with Network drives but also acts as a workaround for the files in `/tmp`, being able to see the real path rather than the snaps own virtual filesystem.

Unfortunately, I don't think there's a good workaround for this this in Pinta or the Snap itself. You might be able to convince the screenshot tool to save somewhere like `$HOME/documents/.tmp`, if you could do that, the snap would be able to view it.

Alternately, you might be able to take the screenshot from Pinta itself in the File > Take Screenshot menu. The exact interface depends upon your desktop environment, as the DE actually handles the request, but it's Wayland capable and depending upon what your DE plugs in, likely able to select specific windows.

**Comment by TIMAI2** [comment]
Unfortunately, the "open with" file save directory is hard coded in xfce4-screenshooter, and I found that the devs locked down files to 600 when saved there (otherwise this would not be an issue) - this could be due to the new version following the upgrade. n.b. the normal save as file directory is easily settable in the config file.

I should be able to write a custom action for xfce4-screenshooter in order to 1. chmod the screenshot file to 666, then 2. open it with pinta.

My no fix workaround is to copy the screen shot to the clipboard, then open pinta and paste it...

I will have a play and come back on this.

**Comment by TIMAI2** [comment]
Best I could come up with was to write a little bash script to call from a keyboard shortcut:

`#!/bin/bash`
`dte=$(date '+%Y-%m-%d_%H-%M-%S')`
`xfce4-screenshooter -r -s ~/Documents/tmp/"screenshot_$dte.png" `
`pinta ~/Documents/tmp/"screenshot_$dte.png"`

Could not get a custom action to work.

I will now need a cron job to empty out the /Documents/tmp directory of screenshot files...

`@reboot /usr/bin/find /home/<user>/Documents/tmp -name "*.png" -type f -mtime +7 -exec rm -f {} \;`

**Comment by TIMAI2** [comment]
Improved the script a bit, so that I could just copy to clipboard instead of always using Pinta (like how xfce4-screenshooter works). Use a zenity dialog.

`#!/bin/bash`
`dte=$(date '+%Y-%m-%d_%H-%M-%S')`
`xfce4-screenshooter -rc -s ~/Documents/tmp/"screenshot_$dte.png" `
`output=$(zenity --list --radiolist --column="Select" --column="Action" TRUE "Copy to Clipboard" FALSE "Open with Pinta")`
`if [ "$output" = "Open with Pinta" ]; then`
`pinta ~/Documents/tmp/"screenshot_$dte.png"`
`fi`

**Comment by JGCarroll** [comment]
Regarding the cron job part of things, you might find it easier to add `$HOME/documents/.tmp` in `/etc/fstab`, set it up as a tmpfs like `/tmp` itself is, and it'll get the same automatic cleanups as `/tmp` does.

`/etc/fstab` could save you another way, as you could in theory just create a bind mount in $HOME to `/tmp`,  let the screenshot tool keep saving in `/tmp`, but when you invoke Pinta via CLI, give it the $HOME path. Effectively this is just a symlink which  is nothing special by itself, but a regular symlink will be seen as a sandbox violation whereas a bind mount in $HOME wouldn't.

Either of these options should mean you don't have to worry about a cron job to cleanup files, and the second might be helpful if you have other snaps where the `/tmp` quirk comes into play, as that's a quirk of every `strict` snap, beyond just Pinta, but this should apply equally for them all.

**Comment by TIMAI2** [comment]
Thanks for the tips, will try them out when I get the time, but my workarounds are doing what I need for now. Will close.

**Comment by TIMAI2** [comment]
Follow up, tried the bind approach in fstab, and this works well:

- Have a folder called `~/Documents/tmp`  (calling it `tmp` is important)
- Added the following to /etc/fstab `/tmp /home/<user>/Documents/tmp none bind,nofail`
- Reboot. The /tmp folder should now be displayed in ~/Documents/tmp
- Create custom action in xfce4-screenshooter: Pinta - `pinta ~/Documents/%f` - `%f` will be `/tmp/<filename>`, which is why you need your bound directory to be called tmp as well.
- Use the custom action to open Pinta with the screenshot.

I generally select regions, so have PrtSc key set to `xfce4-screenshooter -r` and Alt-PrtSc set to `xfce4-screenshooter -w`
